# Nacre zsh config (oh-my-zsh based)
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""                # the prompt is defined below
DISABLE_AUTO_TITLE="true"   # the tab title is set below
plugins=(git fzf zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
export PATH="$HOME/.local/bin:$PATH"
export EDITOR=vim

alias ll='ls -alh'

# Personal aliases/settings that are not part of this repo
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

# A terminal that opens in the home directory starts in ~/code
[[ $PWD == $HOME && -d ~/code ]] && cd ~/code

# ---- Key bindings (oh-my-zsh already covers Ctrl+arrows, history, completion)
bindkey '^[[1;3D' backward-word      # Alt+Left
bindkey '^[[1;3C' forward-word       # Alt+Right
bindkey '^[[H' beginning-of-line     # Home
bindkey '^[[F' end-of-line           # End

# Shift+Enter inserts a newline (the terminal sends ESC+Enter)
_nacre_newline() { LBUFFER+=$'\n' }
zle -N _nacre_newline
bindkey '^[^M' _nacre_newline

# ---- Tab title: name of the current directory
autoload -Uz add-zsh-hook
_nacre_title() { print -Pn '\e]0;%1~\a' }
add-zsh-hook precmd _nacre_title

# ---- Prompt: user@host cwd git:(branch) *  %   (single line, dark 256 colors)
_nacre_git() {
  local b dirty=''
  b=$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null) || return
  # "git status" is slow on Windows drives (/mnt/*): show only the branch there
  if [[ $PWD != /mnt/* ]]; then
    [[ -n $(GIT_OPTIONAL_LOCKS=0 git status --porcelain 2>/dev/null | head -1) ]] && dirty=' %F{221}*'
  fi
  print -rn -- " %F{179}git:(%F{203}${b//\%/%%}%F{179})%f${dirty}"
}
setopt prompt_subst
PROMPT='%F{114}%n@%m%f %F{75}%~%f$(_nacre_git) %F{213}%#%f '
RPROMPT=''
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=240'

# ---- macOS-style open: folders/files open in Windows, URLs in the default browser
open() {
  if [[ $# -eq 0 ]]; then explorer.exe .; return 0; fi
  local a rc=0
  for a in "$@"; do
    if [[ $a == http://* || $a == https://* ]]; then
      (cd /mnt/c && cmd.exe /c start "" "$a") >/dev/null 2>&1
    elif [[ -e $a ]]; then
      explorer.exe "$(wslpath -w "$(realpath "$a")")"   # explorer.exe always exits with 1, ignore it
    else
      print -u2 "open: $a: No such file or directory"; rc=1
    fi
  done
  return $rc
}
